import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import test from 'node:test';

const readSource = (path) =>
  readFileSync(new URL(path, import.meta.url), 'utf8');

test('custom cursor runtime is split into focused hooks with documented offsets', () => {
  const source = readSource('./CustomCursor.tsx');

  assert.match(source, /const createCustomCursorRuntime = /);
  assert.match(source, /const useCursorPreviewRouteReset = /);
  assert.match(source, /const useCursorEventListeners = /);
  assert.match(source, /const useCursorIntroMessageObserver = /);
  assert.match(source, /baseline 22px type scale/);

  const eventHookStart = source.indexOf('const useCursorEventListeners = ');
  assert.notEqual(eventHookStart, -1);
  const eventHookSource = source.slice(eventHookStart);
  assert.match(eventHookSource, /window\.addEventListener\('resize'/);
  assert.match(eventHookSource, /document\.addEventListener\('pointermove'/);
});

test('custom cursor caches layout measurements outside the pointer frame', () => {
  const source = readSource('./CustomCursor.tsx');
  const pointerFrameStart = source.indexOf('const runPointerFrame = () => {');
  const scheduleFrameStart = source.indexOf('const schedulePointerFrame = () => {');

  assert.notEqual(pointerFrameStart, -1);
  assert.notEqual(scheduleFrameStart, -1);

  const pointerFrameSource = source.slice(pointerFrameStart, scheduleFrameStart);

  assert.match(source, /const refreshPreviewSize = /);
  assert.match(source, /const refreshMessageSize = /);
  assert.match(source, /let activeMagneticRect: DOMRect \| null = null/);
  assert.doesNotMatch(pointerFrameSource, /offsetWidth|offsetHeight/);
  assert.doesNotMatch(pointerFrameSource, /getBoundingClientRect/);
});

test('cursor message uses inverted theme tokens without inverse vars', () => {
  const source = readSource('./CustomCursor.module.sass');
  const messageStart = source.indexOf('.message');
  const previewStart = source.indexOf('.preview');

  assert.notEqual(messageStart, -1);
  assert.notEqual(previewStart, -1);

  const messageSource = source.slice(messageStart, previewStart);

  assert.match(messageSource, /background: var\(--theme-type\)/);
  assert.match(messageSource, /color: var\(--theme-bg\) !important/);
  assert.doesNotMatch(messageSource, /background: currentColor/);
  assert.doesNotMatch(messageSource, /--inversed-/);
});

test('title switcher registers visibility listener once and tracks title in a ref', () => {
  const source = readSource('./TitleSwitcher.tsx');

  assert.match(source, /useRef/);
  assert.doesNotMatch(source, /useState/);
  assert.match(source, /originalTitleRef\.current/);
  assert.match(
    source,
    /document\.addEventListener\('visibilitychange', handleVisibilityChange\)[\s\S]*\}, \[\]\);/,
  );
});

test('markdown word swap renderers are generated by a shared factory', () => {
  const source = readSource('./TheMarkdown/TheMarkdown.tsx');

  assert.match(source, /const createWordSwapComponent = /);
  assert.match(source, /const wordSwapComponents = /);
  assert.ok(
    (source.match(/renderWordSwapChildren/g) || []).length <= 3,
    'renderWordSwapChildren should only appear in the import, factory, and link renderer',
  );
});

test('markdown component map stays module-level and receives locale as a prop', () => {
  const source = readSource('./TheMarkdown/TheMarkdown.tsx');

  assert.doesNotMatch(source, /^'use client';/);
  assert.doesNotMatch(source, /useStore/);
  assert.doesNotMatch(source, /useMemo/);
  assert.match(source, /locale: Locale;/);
  assert.match(source, /const wordSwapComponents = Object\.fromEntries/);
});

test('project slug prop uses primitive string type', () => {
  const source = readSource('./BlokProject.tsx');

  assert.match(source, /slug\?: string;/);
  assert.doesNotMatch(source, /slug\?: String;/);
});

test('locale initializer uses passive effects for store-only locale state', () => {
  const source = readSource('./LocaleInitializer.tsx');

  assert.match(source, /import \{ useEffect \} from 'react';/);
  assert.doesNotMatch(source, /useLayoutEffect/);
  assert.match(source, /useEffect\(\(\) => \{\s*const detected = detectInitialLocale\(\);\s*setLocale\(detected\);/);
});

test('intro and cursor loader do not keep dead fallback markup or IE listener paths', () => {
  const introSource = readSource('./storyblok/BlokIntro/BlokIntro.tsx');
  const loaderSource = readSource('./CursorLoader.tsx');

  assert.doesNotMatch(introSource, /\{\/\*[\s\S]*moreButton/);
  assert.doesNotMatch(loaderSource, /\.addListener\(/);
  assert.doesNotMatch(loaderSource, /\.removeListener\(/);
});

test('project list sort/search helpers stay hoisted outside the client component', () => {
  const source = readSource('./storyblok/BlokProjectListClient.tsx');
  const componentIndex = source.indexOf('export default function BlokProjectListClient');

  for (const helperName of [
    'getTimeValue',
    'getCategoryValue',
    'getSearchableText',
  ]) {
    const helperIndex = source.indexOf(`const ${helperName} = `);
    assert.notEqual(helperIndex, -1, `${helperName} should exist`);
    assert.ok(
      helperIndex < componentIndex,
      `${helperName} should be defined before the component`,
    );
  }
});

test('home project thumbnail wrapper owns fixed hover thumbnails without cursor preview', () => {
  const projectSource = readSource('./BlokProject.tsx');
  const listSource = readSource('./storyblok/BlokProjectListClient.tsx');
  const listStyleSource = readSource('./storyblok/BlokProjectListClient.module.sass');
  const globalStyleSource = readSource('../assets/styles/global.sass');
  const wrapperSource = readSource('./storyblok/ThumbnailWrapper.tsx');
  const wrapperStyleSource = readSource('./storyblok/ThumbnailWrapper.module.sass');
  const globalProjectListBlock =
    globalStyleSource.match(/&-ProjectList\n[\s\S]*?&-Filter/)?.[0] || '';
  const globalProjectBlock =
    globalStyleSource.match(/&-Project\n[\s\S]*?&-Highlights/)?.[0] || '';
  const activeProjectLayerBlock =
    listStyleSource.match(/\.activeProjectLayer\n[\s\S]*?\.activeProjectRow/)?.[0] || '';
  const imageClassStart = wrapperStyleSource.indexOf('.thumbnailImage');
  const imageClassEnd = wrapperStyleSource.indexOf('@keyframes', imageClassStart);
  const imageClassSource = wrapperStyleSource.slice(imageClassStart, imageClassEnd);
  const leavingClassStart = wrapperStyleSource.indexOf('.thumbnailItemLeaving');
  const leavingClassEnd = wrapperStyleSource.indexOf('.thumbnailImage', leavingClassStart);
  const leavingClassSource = wrapperStyleSource.slice(
    leavingClassStart,
    leavingClassEnd,
  );

  assert.match(projectSource, /disableCursorPreview\?: boolean;/);
  assert.match(projectSource, /hideProjectCopy\?: boolean;/);
  assert.match(projectSource, /onProjectHover\?: \(element: HTMLDivElement\) => void;/);
  assert.match(projectSource, /const hasCursorPreview = !!cursorPreviewImage && !disableCursorPreview;/);
  assert.match(projectSource, /onProjectHover\?\.\(event\.currentTarget\);/);
  assert.match(projectSource, /data-hide-copy=\{hideProjectCopy \? true : undefined\}/);
  assert.match(listSource, /disableCursorPreview/);
  assert.match(listSource, /hideProjectCopy=\{activeProjectSlug === item\.slug\}/);
  assert.match(listSource, /activeProjectOverlay/);
  assert.match(wrapperSource, /children\?: ReactNode;/);
  assert.match(wrapperSource, /children\}/);
  assert.match(wrapperSource, /\{children\}/);
  assert.match(listSource, /activeProjectElementRef/);
  assert.match(listSource, /activeProjectElementRef\.current = element;/);
  assert.match(listSource, /window\.requestAnimationFrame/);
  assert.match(listSource, /window\.addEventListener\('scroll', updateOverlayPosition, \{ passive: true \}\)/);
  assert.match(listSource, /window\.addEventListener\('resize', updateOverlayPosition\)/);
  assert.match(listSource, /getBoundingClientRect\(\)/);
  assert.match(listSource, /<ThumbnailWrapper[\s\S]*\{activeProjectOverlay && \(/);
  assert.match(listSource, /className=\{styles\.activeProjectLayer\} aria-hidden="true" inert/);
  assert.match(listSource, /style=\{activeProjectOverlayStyle\}/);
  assert.doesNotMatch(listStyleSource, /:global\(\.blok-Project:hover\)/);
  assert.match(listStyleSource, /:global\(\.blok-Project\[data-hide-copy='true'\] \.row > \.column\)/);
  assert.match(listStyleSource, /opacity: 0/);
  assert.match(listStyleSource, /\.activeProjectLayer/);
  assert.match(listStyleSource, /pointer-events: none/);
  assert.match(listStyleSource, /\.activeProjectRow/);
  assert.doesNotMatch(listStyleSource, /transform: translateY\(-1\.8rem\)/);
  assert.match(activeProjectLayerBlock, /display: contents/);
  assert.doesNotMatch(activeProjectLayerBlock, /z-index: 1/);
  assert.doesNotMatch(activeProjectLayerBlock, /color: #fff/);
  assert.doesNotMatch(activeProjectLayerBlock, /mix-blend-mode: difference/);
  assert.match(projectSource, /zIndex: isHoverActive \? 9998 : stackIndex/);
  assert.doesNotMatch(projectSource, /stackIndex \?\? 0/);
  assert.match(listStyleSource, /isolation: auto !important/);
  assert.match(listStyleSource, /:global\(\.blok-Project \.row > \.column\)[\s\S]*mix-blend-mode: difference/);
  assert.match(listStyleSource, /background: transparent !important/);
  assert.match(listStyleSource, /border-color: transparent !important/);
  assert.match(listStyleSource, /border-left-width: 0 !important/);
  assert.match(listStyleSource, /border-right-width: 0 !important/);
  assert.match(listStyleSource, /:global\(\.blok-Project \.column-Icons\)/);
  assert.match(listStyleSource, /opacity: 0 !important/);
  assert.doesNotMatch(globalProjectListBlock, /\.blok-Project:hover[\s\S]*transform: translateY\(-1\.8rem\) !important/);
  assert.doesNotMatch(globalProjectListBlock, /padding-bottom: calc\(3\.95rem \* 0\.5\)/);
  assert.doesNotMatch(globalProjectBlock, /padding-bottom: calc\(3\.95rem \* 0\.5\)/);
  assert.doesNotMatch(globalProjectBlock, /margin-bottom: calc\(-3\.95rem \* 0\.5\)/);
  assert.doesNotMatch(globalProjectBlock, /\n    transition: transform/);
  assert.match(listSource, /<ThumbnailWrapper/);
  assert.match(listSource, /<\/ThumbnailWrapper>/);
  assert.match(listSource, /projects=\{projects\}/);
  assert.match(listSource, /hoverEvent=\{hoverEvent\}/);
  assert.match(listSource, /leaveEvent=\{leaveEvent\}/);
  const thumbnailWrapperIndex = listSource.indexOf(
    '<ThumbnailWrapper\n        projects={projects}',
  );
  const projectListIndex = listSource.indexOf(
    '<div\n        className={`blok blok-Animate blok-ProjectList',
  );

  assert.notEqual(thumbnailWrapperIndex, -1);
  assert.notEqual(projectListIndex, -1);
  assert.ok(
    thumbnailWrapperIndex < projectListIndex,
    'thumbnail wrapper must render outside the animated project list container',
  );
  assert.doesNotMatch(listSource, /const getRandomThumbnailPosition = /);
  assert.match(wrapperSource, /projects: ProjectData\[\];/);
  assert.match(wrapperSource, /const getRandomThumbnailPosition = /);
  assert.match(wrapperSource, /const getThumbnailSize = /);
  assert.match(wrapperSource, /getProjectThumbnailSrc/);
  assert.match(wrapperSource, /import Image from 'next\/image';/);
  assert.match(wrapperSource, /<Image/);
  assert.match(wrapperSource, /fill/);
  assert.match(wrapperSource, /unoptimized/);
  assert.match(wrapperSource, /sizes="\(max-width: 770px\) calc\(100vw - var\(--spacing-base\) \* 2\), 25vw"/);
  assert.match(wrapperSource, /HOVER_THUMBNAIL_LIFETIME_MS = 1250/);
  assert.match(wrapperSource, /Math\.min\(viewportWidth, viewportHeight\) - padding \* 2/);
  assert.match(wrapperSource, /viewportWidth \* 0\.25 - padding/);
  assert.match(wrapperStyleSource, /\.thumbnailWrapper/);
  assert.match(wrapperStyleSource, /position: fixed/);
  assert.match(wrapperStyleSource, /width: 100vw/);
  assert.match(wrapperStyleSource, /height: 100vh/);
  assert.match(wrapperStyleSource, /pointer-events: none/);
  assert.match(wrapperStyleSource, /isolation: auto/);
  assert.doesNotMatch(wrapperStyleSource, /\bborder:/);
  assert.match(wrapperStyleSource, /width: min\(36rem, max\(18rem, calc\(22vw - var\(--spacing-base\)\)\), max\(0px, calc\(100vw - var\(--spacing-base\) \* 2\)\), max\(0px, calc\(100vh - var\(--spacing-base\) \* 2\)\)\)/);
  assert.match(wrapperStyleSource, /aspect-ratio: 1 \/ 1/);
  assert.match(wrapperStyleSource, /\.thumbnailImage/);
  assert.match(wrapperStyleSource, /aspect-ratio: 4 \/ 3/);
  assert.match(wrapperStyleSource, /border-radius: 10px/);
  assert.match(wrapperStyleSource, /overflow: hidden/);
  assert.match(wrapperStyleSource, /object-fit: contain/);
  assert.match(wrapperStyleSource, /\.thumbnailItemLeaving/);
  assert.match(leavingClassSource, /opacity: 1/);
  assert.match(leavingClassSource, /animation: thumbnailItemExit 0\.3s ease 0\.95s forwards/);
  assert.doesNotMatch(imageClassSource, /transform:/);
  assert.doesNotMatch(imageClassSource, /animation:/);
  assert.doesNotMatch(wrapperStyleSource, /thumbnailImageEnter/);
});

test('blok chrome memoization uses React shallow comparison only', () => {
  const headSource = readSource('./BlokHead/BlokHead.tsx');
  const topPanelSource = readSource('./BlokSidePanels/TopPanel.tsx');
  const sidePanelsSource = readSource('./BlokSidePanels/BlokSidePanels.tsx');

  assert.doesNotMatch(headSource, /haveProjectsChanged/);
  assert.match(headSource, /const BlokHead = memo\(BlokHeadComponent\);/);
  assert.doesNotMatch(topPanelSource, /prevProps|nextProps/);
  assert.match(topPanelSource, /const TopPanel = memo\(TopPanelComponent\);/);
  assert.doesNotMatch(sidePanelsSource, /prevProps|nextProps/);
  assert.match(sidePanelsSource, /const BlokSidePanels = memo\(BlokSidePanelsComponent\);/);
});

test('app initializer updates theme meta directly and observes body once', () => {
  const source = readSource('./AppInitStore.tsx');

  assert.match(source, /const applyThemeMetaColor = \(theme: Theme\) => \{/);
  assert.match(source, /applyThemeMetaColor\(theme\);/);
  assert.doesNotMatch(source, /bodyTheme/);
  assert.match(source, /document\.body\.getAttribute\('data-theme'\)/);
  assert.match(source, /const observer = new MutationObserver\(updateMetaThemeColor\)/);
  assert.match(
    source,
    /observer\.observe\(body,[\s\S]*observer\.disconnect\(\);[\s\S]*\}, \[\]\);/,
  );
});

test('column slider memoizes active images and renders indicators once', () => {
  const source = readSource('./storyblok/ColumnSlider.tsx');
  const activeImagesIndex = source.indexOf('const activeImages = useMemo(');
  const mapIndex = source.indexOf('activeImages.map');
  const indicatorsIndex = source.indexOf('<SliderIndicators');

  assert.notEqual(activeImagesIndex, -1, 'activeImages should be memoized');
  assert.ok(
    activeImagesIndex < mapIndex,
    'activeImages should be derived before rendering slides',
  );
  assert.equal(
    (source.match(/<SliderIndicators/g) || []).length,
    1,
    'SliderIndicators should be rendered once per slider',
  );
  assert.ok(
    indicatorsIndex > source.lastIndexOf('})}', source.indexOf('{blok.caption')),
    'SliderIndicators should be outside the activeImages.map render loop',
  );
});

test('static locale labels are passed as props instead of reading the store', () => {
  const files = [
    './BlokFilter/BlokFilter.tsx',
    './BlokFooter/BlokFooter.tsx',
    './BlokFooter/FooterNav.tsx',
    './TheMarkdown/TheMarkdown.tsx',
    './Newsletter/Newsletter.tsx',
  ];

  for (const file of files) {
    const source = readSource(file);
    assert.doesNotMatch(source, /useStore/);
    assert.match(source, /locale/);
  }

  assert.doesNotMatch(readSource('./BlokFooter/FooterNav.tsx'), /^'use client';/);
  assert.doesNotMatch(readSource('./TheMarkdown/TheMarkdown.tsx'), /^'use client';/);
  assert.match(readSource('./storyblok/BlokProjectList.tsx'), /locale=\{locale\}/);
});

test('retired service worker is unregistered and not cached immutably', () => {
  const source = readSource('./ClientEnhancements.tsx');
  const netlifySource = readFileSync(new URL('../../netlify.toml', import.meta.url), 'utf8');
  const serviceWorkerFile = new URL('../../public/sw.js', import.meta.url);

  assert.equal(existsSync(serviceWorkerFile), false);
  assert.doesNotMatch(source, /serviceWorker\.register/);
  assert.match(source, /serviceWorker\.getRegistrations/);
  assert.match(source, /registration\.unregister/);
  assert.match(source, /driesbos-webapp-/);
  assert.match(netlifySource, /for = "\/sw\.js"[\s\S]*Cache-Control = "no-store, max-age=0, must-revalidate"/);
});
