import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const readSource = (path) =>
  readFileSync(new URL(path, import.meta.url), 'utf8');

test('custom cursor runtime is split into focused hooks with documented offsets', () => {
  const source = readSource('./CustomCursor.tsx');

  assert.match(source, /const createCustomCursorRuntime = /);
  assert.match(source, /const useCursorPreviewRouteReset = /);
  assert.match(source, /const useCursorEventListeners = /);
  assert.match(source, /const useCursorIntroMessageObserver = /);
  assert.match(source, /baseline 22px type scale/);

  const eventHookStart = source.indexOf('const useCursorEventListeners = ');
  assert.notEqual(eventHookStart, -1);
  const eventHookSource = source.slice(eventHookStart);
  assert.match(eventHookSource, /window\.addEventListener\('resize'/);
  assert.match(eventHookSource, /document\.addEventListener\('pointermove'/);
});

test('cursor message uses inverted theme tokens without inverse vars', () => {
  const source = readSource('./CustomCursor.module.sass');
  const messageStart = source.indexOf('.message');
  const previewStart = source.indexOf('.preview');

  assert.notEqual(messageStart, -1);
  assert.notEqual(previewStart, -1);

  const messageSource = source.slice(messageStart, previewStart);

  assert.match(messageSource, /background: var\(--theme-type\)/);
  assert.match(messageSource, /color: var\(--theme-bg\) !important/);
  assert.doesNotMatch(messageSource, /background: currentColor/);
  assert.doesNotMatch(messageSource, /--inversed-/);
});

test('title switcher registers visibility listener once and tracks title in a ref', () => {
  const source = readSource('./TitleSwitcher.tsx');

  assert.match(source, /useRef/);
  assert.doesNotMatch(source, /useState/);
  assert.match(source, /originalTitleRef\.current/);
  assert.match(
    source,
    /document\.addEventListener\('visibilitychange', handleVisibilityChange\)[\s\S]*\}, \[\]\);/,
  );
});

test('markdown word swap renderers are generated by a shared factory', () => {
  const source = readSource('./TheMarkdown/TheMarkdown.tsx');

  assert.match(source, /const createWordSwapComponent = /);
  assert.match(source, /const wordSwapComponents = /);
  assert.ok(
    (source.match(/renderWordSwapChildren/g) || []).length <= 3,
    'renderWordSwapChildren should only appear in the import, factory, and link renderer',
  );
});

test('markdown component map is memoized by locale', () => {
  const source = readSource('./TheMarkdown/TheMarkdown.tsx');

  assert.match(source, /import \{[^}]*useMemo[^}]*\} from 'react';/);
  assert.match(source, /const components: Components = useMemo\(\(\) => \(\{/);
  assert.match(source, /\}\), \[locale\]\);/);
});

test('project slug prop uses primitive string type', () => {
  const source = readSource('./BlokProject.tsx');

  assert.match(source, /slug\?: string;/);
  assert.doesNotMatch(source, /slug\?: String;/);
});

test('locale initializer uses passive effects for store-only locale state', () => {
  const source = readSource('./LocaleInitializer.tsx');

  assert.match(source, /import \{ useEffect \} from 'react';/);
  assert.doesNotMatch(source, /useLayoutEffect/);
  assert.match(source, /useEffect\(\(\) => \{\s*const detected = detectInitialLocale\(\);\s*setLocale\(detected\);/);
});

test('intro and cursor loader do not keep dead fallback markup or IE listener paths', () => {
  const introSource = readSource('./storyblok/BlokIntro/BlokIntro.tsx');
  const loaderSource = readSource('./CursorLoader.tsx');

  assert.doesNotMatch(introSource, /\{\/\*[\s\S]*moreButton/);
  assert.doesNotMatch(loaderSource, /\.addListener\(/);
  assert.doesNotMatch(loaderSource, /\.removeListener\(/);
});

test('project list sort/search helpers stay hoisted outside the client component', () => {
  const source = readSource('./storyblok/BlokProjectListClient.tsx');
  const componentIndex = source.indexOf('export default function BlokProjectListClient');

  for (const helperName of [
    'getTimeValue',
    'getCategoryValue',
    'getSearchableText',
  ]) {
    const helperIndex = source.indexOf(`const ${helperName} = `);
    assert.notEqual(helperIndex, -1, `${helperName} should exist`);
    assert.ok(
      helperIndex < componentIndex,
      `${helperName} should be defined before the component`,
    );
  }
});

test('blok action drives repeated about icons from one shared animation frame', () => {
  const actionSource = readSource('./BlokAction.tsx');
  const iconSource = readSource('./Icons/IconAbout.tsx');

  assert.match(actionSource, /window\.setInterval/);
  assert.equal(
    (actionSource.match(/window\.setInterval/g) || []).length,
    1,
    'BlokAction should create one shared animation clock',
  );
  assert.match(actionSource, /frameIndex=\{iconFrameIndex\}/);
  assert.doesNotMatch(actionSource, /<IconAbout[^>]*animate/);
  assert.match(iconSource, /frameIndex\?: number/);
});
